### ISSUE TITLE
参数"endpoint"为空指针。

### ISSUE THREAD

**Issue by mushroom1113** [XieXianbin/UEditor-for-aliyun-OSS#8]
java.lang.NullPointerException: 参数"endpoint"为空指针。
    at com.aliyun.common.utils.CodingUtils.assertParameterNotNull(CodingUtils.java:17)
    at com.aliyun.common.utils.CodingUtils.assertStringNotNullOrEmpty(CodingUtils.java:23)
    at com.aliyun.openservices.oss.OSSClient.<init>(OSSClient.java:128)
    at com.aliyun.openservices.oss.OSSClient.<init>(OSSClient.java:111)
    at com.qikemi.packages.alibaba.aliyun.oss.OSSClientFactory.createOSSClient(OSSClientFactory.java:27)
    at com.baidu.ueditor.upload.Uploader.doExec(Uploader.java:54)
    at com.baidu.ueditor.ActionEnter.invoke(ActionEnter.java:80)
    at com.baidu.ueditor.ActionEnter.exec(ActionEnter.java:49)
    at org.apache.jsp.static_.ueditor.jsp.controller_jsp._jspService(controller_jsp.java:118)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)

**Comment by mushroom1113** [comment]
拉下代码调试了，OSSKey.properties少了  ossCliendEndPoint

**Comment by xiexianbin** [comment]
请确认一下你的版本和配置是否匹配。
